
[database]
  auto_connect = true
  backup = "/path/to/backup/database"
  init = "/path/to/taggerSchemaDef.sql"
  path = "/path/to/database"

[descriptor_tree]
  main_request = "#META#"

[selection]
  buffer_size = 30
  display_parents = 1

[style]
  [style.font]
    regular = "/path/to/font.ttf"
    thin = "/path/to/font.ttf"
    bold = "/path/to/font.ttf"